name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install uv
        uv pip install -r requirements.txt

    - name: Deploy Streamlit
      run: |
        pip install streamlit
        streamlit run app.py --server.port 8501

    - name: Keep Action Running
      run: sleep infinity
